"""<descriptive message>

Revision ID: 22f02ed267e0
Revises: 
Create Date: 2023-06-05 22:27:49.536085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f02ed267e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_job_image', sa.String(), nullable=True),
    sa.Column('male_job_sprite_up', sa.String(), nullable=True),
    sa.Column('male_job_sprite_left', sa.String(), nullable=True),
    sa.Column('male_job_sprite_right', sa.String(), nullable=True),
    sa.Column('male_job_sprite_down', sa.String(), nullable=True),
    sa.Column('female_job_image', sa.String(), nullable=True),
    sa.Column('female_job_sprite_up', sa.String(), nullable=True),
    sa.Column('female_job_sprite_left', sa.String(), nullable=True),
    sa.Column('female_job_sprite_right', sa.String(), nullable=True),
    sa.Column('female_job_sprite_down', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('lvl', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mg', sa.Integer(), nullable=True),
    sa.Column('strg', sa.Integer(), nullable=True),
    sa.Column('defn', sa.Integer(), nullable=True),
    sa.Column('mind', sa.Integer(), nullable=True),
    sa.Column('intl', sa.Integer(), nullable=True),
    sa.Column('spd', sa.Integer(), nullable=True),
    sa.Column('evad', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_image', sa.String(), nullable=True),
    sa.Column('monster_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('region', sa.Enum('Nemar', 'Cyneil', 'Corize', 'Naurra Isles', 'Ausstero', name='regions'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_stats_id'], ['job_stats.id'], name=op.f('fk_characters_job_stats_id_job_stats')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mg', sa.Integer(), nullable=True),
    sa.Column('strg', sa.Integer(), nullable=True),
    sa.Column('defn', sa.Integer(), nullable=True),
    sa.Column('mind', sa.Integer(), nullable=True),
    sa.Column('intl', sa.Integer(), nullable=True),
    sa.Column('spd', sa.Integer(), nullable=True),
    sa.Column('evad', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_stats_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_inventories_character_id_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.drop_table('monster_stats')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('monsters')
    op.drop_table('job_stats')
    # ### end Alembic commands ###
